### ISSUE TITLE
Не выбрасывается исключение при отрицательном стартовом балансе кредитного счета

### ISSUE THREAD

**Issue by MarniaTu** [MarniaTu/JavaQATeamProject#1]
# Описание
Если при создании объекта класса CreditAccount указать отрицательный стартовый баланс, система не выбрасывает исключение.

# Локация дефекта
https://github.com/MarniaTu/JavaQATeamProject/blob/925c62e4189207ab4e3b450fff82abb927793e12/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/MarniaTu/JavaQATeamProject/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19) в ветке credit в IDEA
2. В тестовом классе CreditAccountTest создать метод shouldThrowExceptionIfNegativeInitialBalance 
3. В методе создать объект класса CreditAccount с параметрами:
- отрицательный начальный баланс -10 000
- кредитный лимит 5 000
- ставка кредитования 15
4. Добавить оценку ожидаемого и фактического результата через выброс исключения IllegalArgumentException. 
5. Запустить mvn test.
6. Проверить вывод в консоли. 

*Ожидаемый результат:* выброс исключения о недопустимом значении стартового баланса.
*Фактический результат:* программа не выбрасывает исключение.

# Тест
https://github.com/MarniaTu/JavaQATeamProject/blob/925c62e4189207ab4e3b450fff82abb927793e12/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L18

# Скриншот

![image](https://github.com/MarniaTu/JavaQATeamProject/assets/147163020/e3a8481a-60a2-4845-a775-a9f304cd7ee9)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA Community Edition 2023.2.4
* **Java:** JDK Amazon Corretto 11.0.21

**Comment by AnnaShcherbakova90** [comment]
fixed with https://github.com/MarniaTu/JavaQATeamProject/commit/35a0af4260a2fd8819c2d0ec38661a711656a4ab
