### ISSUE TITLE
В методе pay кредитного счета некорректный результат при попытке уменьшения баланса ниже значения кредитного лимита

### ISSUE THREAD

**Issue by MarniaTu** [MarniaTu/JavaQATeamProject#20]
# Описание
При попытке платежа на сумму, превышающую кредитный лимит, программа позволяет совершить операцию.

# Локация дефекта
https://github.com/MarniaTu/JavaQATeamProject/blob/ddb184c9877b9e4180dd903ae56179de9ea4d335/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/MarniaTu/JavaQATeamProject/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19) в ветке credit в IDEA
2. В тестовом классе CreditAccountTest создать метод shouldNotPayIfExceedsCreditLimit
3. В методе создать объект класса CreditAccount с параметрами:
- начальный баланс 10 000
- кредитный лимит 5 000
- ставка кредитования 10
4. Добавить тестируемый метод pay с суммой платежа 15 500.
5. Запустить mvn test.
6. Проверить вывод в консоли. 

*Ожидаемый результат:* 10 000.
*Фактический результат:* -5 500.

# Тест
https://github.com/MarniaTu/JavaQATeamProject/blob/ddb184c9877b9e4180dd903ae56179de9ea4d335/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L89C17-L89C49

# Скриншот

![image](https://github.com/MarniaTu/JavaQATeamProject/assets/147163020/2aad70bf-a19b-41e1-9488-58ee81fcca72)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA Community Edition 2023.2.4
* **Java:** JDK Amazon Corretto 11.0.21

**Comment by AnnaShcherbakova90** [comment]
fixed with https://github.com/MarniaTu/JavaQATeamProject/issues/19
