### ISSUE TITLE
В методе pay кредитного счета некорректно уменьшается баланс при ожидаемом допустимом отрицательном значении баланса

### ISSUE THREAD

**Issue by MarniaTu** [MarniaTu/JavaQATeamProject#5]
# Описание
Если сумма платежа в пределах кредитного лимита, итоговый баланс равен отрицательному значению суммы платежа.

# Локация дефекта
https://github.com/MarniaTu/JavaQATeamProject/blob/925c62e4189207ab4e3b450fff82abb927793e12/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/MarniaTu/JavaQATeamProject/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19) в ветке credit в IDEA
2. В тестовом классе CreditAccountTest создать метод shouldPay14990WithinCreditLimit
3. В методе создать объект класса CreditAccount с параметрами:
- начальный баланс 10 000
- кредитный лимит 5 000
- ставка кредитования 10
4. Добавить тестируемый метод pay с суммой платежа 14 990.
5. Запустить mvn test.
6. Проверить вывод в консоли. 

*Ожидаемый результат:* -4 990.
*Фактический результат:* -14 990.

# Тест
https://github.com/MarniaTu/JavaQATeamProject/blob/925c62e4189207ab4e3b450fff82abb927793e12/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L74

# Скриншот

![image](https://github.com/MarniaTu/JavaQATeamProject/assets/147163020/41b18a79-7b9f-497d-b84e-994de10dd085)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA Community Edition 2023.2.4
* **Java:** JDK Amazon Corretto 11.0.21

**Comment by AnnaShcherbakova90** [comment]
fixed with https://github.com/MarniaTu/JavaQATeamProject/issues/4
