### ISSUE TITLE
В методе yearChange кредитного счета некорректный результат при начислении процентов на нулевой баланс

### ISSUE THREAD

**Issue by MarniaTu** [MarniaTu/JavaQATeamProject#8]
# Описание
Если начальный баланс кредитного счета уменьшать до нулевого баланса, проценты начисляются на отрицательное значение суммы платежа, равной начальному балансу.

# Локация дефекта
https://github.com/MarniaTu/JavaQATeamProject/blob/925c62e4189207ab4e3b450fff82abb927793e12/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82
https://github.com/MarniaTu/JavaQATeamProject/blob/925c62e4189207ab4e3b450fff82abb927793e12/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/MarniaTu/JavaQATeamProject/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19) в ветке credit в IDEA
2. В тестовом классе CreditAccountTest создать метод shouldNotCalculateYearChangeFromZeroBalance
3. В методе создать объект класса CreditAccount с параметрами:
- начальный баланс 10 000
- кредитный лимит 5 000
- ставка кредитования 15
4. Добавить метод pay с суммой платежа 10 000.
5. Добавить тестируемый метод yearChange.
6. Запустить mvn test.
7. Проверить вывод в консоли. 

*Ожидаемый результат:* 0, так как проценты должны начисляться только на отрицательный баланс кредитного счета.
*Фактический результат:* -1 500.

# Тест
https://github.com/MarniaTu/JavaQATeamProject/blob/925c62e4189207ab4e3b450fff82abb927793e12/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L139

# Скриншот

![image](https://github.com/MarniaTu/JavaQATeamProject/assets/147163020/544f9ab5-0e1d-4347-b15a-9933ba3a9e90)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA Community Edition 2023.2.4
* **Java:** JDK Amazon Corretto 11.0.21

**Comment by AnnaShcherbakova90** [comment]
fixed with https://github.com/MarniaTu/JavaQATeamProject/issues/7
