### ISSUE TITLE
В методе yearChange кредитного счета некорректный результат начисления процентов на положительный баланс

### ISSUE THREAD

**Issue by MarniaTu** [MarniaTu/JavaQATeamProject#9]
# Описание
Если баланс кредитного счета остается положительным, проценты начисляются по формуле для отрицательного баланса кредитного счета.

# Локация дефекта
https://github.com/MarniaTu/JavaQATeamProject/blob/925c62e4189207ab4e3b450fff82abb927793e12/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/MarniaTu/JavaQATeamProject/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19) в ветке credit в IDEA
2. В тестовом классе CreditAccountTest создать метод shouldNotCalculateYearChangeFromPositiveBalance
3. В методе создать объект класса CreditAccount с параметрами:
- начальный баланс 10 000
- кредитный лимит 5 000
- ставка кредитования 16
4. Добавить тестируемый метод yearChange.
5. Запустить mvn test.
6. Проверить вывод в консоли. 

*Ожидаемый результат:* 0, так как проценты начисляются только на отрицательный баланс кредитного счета.
*Фактический результат:* 1 600.

# Тест
https://github.com/MarniaTu/JavaQATeamProject/blob/925c62e4189207ab4e3b450fff82abb927793e12/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L149

# Скриншот

![image](https://github.com/MarniaTu/JavaQATeamProject/assets/147163020/8d12adbc-cc28-482e-944c-80c65741f080)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA Community Edition 2023.2.4
* **Java:** JDK Amazon Corretto 11.0.21

**Comment by AnnaShcherbakova90** [comment]
fixed with https://github.com/MarniaTu/JavaQATeamProject/issues/7
